### ISSUE TITLE
On/Off

### ISSUE THREAD

**Issue by Red1994** [sj26/homebridge-intesisbox#4]
Great plug in - thanks! 
Is it possible to turn on and off (based on existing heat/cool/auto mode) by single tap of homekit icon without having to the scroll to heat/cool/auto each time?  I think a long press of the icon opens the mode and temperature setting.

This is the behavior of the intesisweb plugin.  I have switched from intesisweb to intesisbox as I was having connection issues to the intesisweb cloud.

thanks

**Comment by sj26** [comment]
No, sorry, that's up to Homekit's interface.

I use Siri and say something like "heat up the house" or "cool down the house" or "turn on the aircon".
